name: Check UTF-8

# This workflow is triggered on pushes to the repository.
on: push

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: ./check_utf8.sh
